language: ruby
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=spinach DB=mysql
    - TASK=spec DB=mysql
    - TASK=jasmine:ci DB=mysql
    - TASK=spinach DB=postgresql
    - TASK=spec DB=postgresql
    - TASK=jasmine:ci DB=postgresql
before_install:
  - sudo apt-get install libicu-dev -y
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
services:
  - redis-server
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
notifications:
  email: false
